# Generated by Django 4.2.7 on 2023-11-25 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='username',
        ),
    ]
